services:
  db:
    image: postgres:15.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - db-network
  api:
    image: node:16.19.1
    volumes:
      - ../api:/app
    working_dir: /app
    ports:
      - 3001:3001
    networks:
      - db-network
    command: npm start
    depends_on:
      - db

volumes:
  db-data:


networks:
  db-network:
