services:
  db:
    image: postgres:15.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - ENV=DOCKER
    networks:
      - intranet
    ports:
      - 5432:5432
  api:
    image: node:16.19.1
    volumes:
      - ../api:/app
    working_dir: /app
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/postgres?schema=cars
      - ENV=DOCKER
    networks:
      - intranet
    command: npm start
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - 3000:3000
  front:
    image: node:16.19.1
    volumes:
      - ../front:/app
    working_dir: /app
    networks:
      - intranet
    depends_on:
      - api
      - db
    command: npm start
    stdin_open: true
    tty: true
    environment:
      - VITE_ROUTE_API=http://${API_HOSTNAME}/api/
      - ENV=DOCKER
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 3306:5432
    networks:
      - intranet
    depends_on:
      - api
      - front
      - db
    stdin_open: true
    tty: true

volumes:
  db-data:


networks:
  intranet:
