services:
  db:
    image: postgres:15.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - db-network
  api:
    image: node:16.19.1
    volumes:
      - ../api:/app
    working_dir: /app
    ports:
      - ${API_PORT}:3000
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:Admlocal1@db:5432/postgres?schema=cars
    networks:
      - db-network
      - internet
    command: npm start
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true # docker run -t
  front:
    image: node:16.19.1
    volumes:
      - ../front:/app
    working_dir: /app
    ports:
      - 80:8080
    networks:
      - internet
    depends_on:
      - api
      - db
    command: npm start
    stdin_open: true
    tty: true
    environment:
      - VITE_ROUTE_API=http://localhost:${API_PORT}/

volumes:
  db-data:

networks:
  db-network:
  internet: