on: 
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to dist
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Create Pull Request
      id: cpr
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: main
        base: dist
        title: "An automatically created PR!"
        labels: automerge

    - name: Merge
      uses: "pascalgn/automerge-action@v0.15.6"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST: ${{ steps.cpr.outputs.number }}
